apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 4  # Adjust this value for scaling tests
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: myflaskapp:latest
        ports:
          - containerPort: 5000
        env:
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
